SRCS = putest.c
OBJS = putest.o

TARGET = putest

TARGET32 = $(TARGET)32-static
TARGET64 = $(TARGET)64-static

BIN = ../bin/arm/linux/

all: $(TARGET32) $(TARGET64)

$(TARGET64): $(SRCS) dockcross-arm64
	./dockcross-arm64 bash -c '$$CC $(SRCS) -o $@ -static'
	mv $@ $(BIN)

$(TARGET32): $(SRCS) dockcross-armv7
	./dockcross-armv7 bash -c '$$CC $(SRCS) -o $@ -static'
	mv $@ $(BIN)

dockcross-arm64:
	docker run --rm dockcross/linux-arm64 > ./dockcross-arm64
	chmod +x ./dockcross-arm64

dockcross-armv7:
	docker run --rm dockcross/linux-armv7 > ./dockcross-armv7
	chmod +x ./dockcross-armv7

clean:
	rm -f dockcross* $(TARGET32) $(TARGET64) $(BIN)/*
